### ISSUE TITLE
Add multi-approval support

### ISSUE THREAD

**Issue by rvandernoort** [homewizard/argo-workflows#1]
# Summary

Replace Suspend/Resume with modified parameter process of approval with an actual account related approval form.
Proposal for https://github.com/argoproj/argo-workflows/issues/12108

## Use Cases

Approving promotion from various environments, but need multi Ops approval before promotion. 

---
**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

---

## Todo:
- [ ] Create `Approvers` list as part of parameters
  - [ ]  Connect it with actual user accounts
  - [ ] (optional) make groups work
- [ ] Replace GUI `Modify parameters` with `Approvers list`
- [ ] Show approval status of all accounts (highlight your own account)
- [ ] Allow approval from your account if that is declared
  - [ ] Save approval for your account
  - [ ] Check if approval is over threshold and merge otherwise
  - [ ] Change `when` clause which now depeneds on the variable (switch to `approval amount` out of list)
    - [ ] (optional) more advanced options
- [ ] (optional) cli support
- [ ] docs
- [ ] tests

**Comment by rvandernoort** [comment]
Short-term: use plugin style instead of directly in core.

**Comment by elwin1234** [comment]
Good point
